# MTH4000 Programming in Python I - Lecture 9
Module Organisers: Dr Matthew Lewis and Prof. Thomas Prellberg

We will now turn towards working with arrays in Python. Solving systems of linear equations is an essential part of mathematics. More about this in Linear Algebra next semester, For now it suffices to say that there are many Linear Algebra functions available in Python. You will find these functions in `scipy.linalg`, with the relevant data type `array` provided by `numpy`. So let us start with importing the relevant modules.

In [2]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt

## Nested Lists, Arrays, Matrices, and All That

### Array data type

The module `numpy` provides the data type `ndarray` for $n$-dimensional arrays. In what follows, we will mainly consider two-dimensional arrays, i.e. matrices.

**A word of caution:** Python also knows a type `array` as part of the module `array`, and also a (deprecated) type `matrix` as part of the module `numpy`. Mixing data of these different types is a bad idea, and I *strongly* urge you to stay with the array type `ndarray` defined in `numpy`.

With the function `numpy.array` we can create an array from a range, tuple, or (nested) list.

In [3]:
l=[0,1,2,3,4,5]

a=np.array(l)

print(l)
print(a) # there are no commas

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


You see that when printed out, this looks slightly differently than for lists. Let us repeat this for two-dimensional arrays, where the array is printed out like a matrix.

In [5]:
l=[[0,1,2],[3,4,5]]

a=np.array(l)

print(l)
print(a)

[[0, 1, 2], [3, 4, 5]]
[[0 1 2]
 [3 4 5]]


As usual, we can query the data type with `type()`.

In [6]:
type(a)

numpy.ndarray

While arrays look like nested lists, they have some more restrictive features when compared with nested lists, to enable faster access and computation. For example, numpy attempts to keep the data types homogeneous as in the next example, where the integer `2` got replaced by the floating point `2.`.

In [8]:
a_int=np.array([[0,1,2],[3,4,5]])
a_float=np.array([[0,1,2.],[3,4,5]])

print(a_int)
print(a_float)

[[0 1 2]
 [3 4 5]]
[[0. 1. 2.]
 [3. 4. 5.]]


We can query the *data* type of the array by using the `.dtype` attribute

In [9]:
a_int.dtype, a_float.dtype

(dtype('int32'), dtype('float64'))

Note that data types of array entries differ from standard Python data types, again mainly to make computations easier and faster to perform. You can find out more [here](https://docs.scipy.org/doc/numpy/user/basics.types.html).

### Creating Arrays

We have already created arrays by converting a (nested) list to an array by using the function `numpy.array()`. Early on in the lectures I already sneaked in a one-dimensional array when I used the function `numpy.linspace()`. You may recall I used it to create evenly spaced $x$-coordinates for plotting. What I really did was create an array with this function.

In [10]:
a=np.linspace(0,10,6)
print(a)
type(a)

[ 0.  2.  4.  6.  8. 10.]


numpy.ndarray

We can also create arrays pre-filled with zeros, ones, or any other value using `numpy.zeros()`, `numpy.ones()`, or `numpy.full()`, respectively.

In [11]:
a=np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [12]:
a=np.zeros((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
a=np.ones((5,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
a=np.full((2,4),3)
print(a)

[[3 3 3 3]
 [3 3 3 3]]


Finally, we can create a square shaped array with ones on the diagonal (i.e. an identity matrix) using the function `numpy.eye()`.

In [15]:
a=np.eye(7)
print(a)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


### Dimension, Shape, and Size

The attribute `.ndim` returns the dimension of an array, and the attribute `.shape` returns the tuple describing the number of rows, columns, etc., and the attribute `.size` returns the total number of entries

In [16]:
a=np.zeros(10)
print(a)
print(a.ndim,a.shape,a.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1 (10,) 10


In [17]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a.ndim,a.shape,a.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2 (2, 5) 10


In [18]:
a=np.full((3,2,4),np.exp(1))
print(a)
print(a.ndim,a.shape,a.size)

[[[2.71828183 2.71828183 2.71828183 2.71828183]
  [2.71828183 2.71828183 2.71828183 2.71828183]]

 [[2.71828183 2.71828183 2.71828183 2.71828183]
  [2.71828183 2.71828183 2.71828183 2.71828183]]

 [[2.71828183 2.71828183 2.71828183 2.71828183]
  [2.71828183 2.71828183 2.71828183 2.71828183]]]
3 (3, 2, 4) 24


### Slicing and Indexing

Indexing and slicing of arrays works just as for plain lists, including the use of negative indices. Numpy's indexing is however more versatile. For example, not only `a[i][j]`, but also `a[i,j]` is allowed.

In [24]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

print(a[2,1]) # first number represents the "column" and the second number represents the "row"
print(a[2][1])

print(a[2])
print(a[2,:])

print(a[:,2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
8
8
[7 8 9]
[7 8 9]
[ 3  6  9 12]


Accessing rows is also just as with lists, and accessing columnns also works (as opposed to lists, where this concept does not make sense). We simply put placeholders `:` into the position of the index corresponding to the data that we want to extract.

In [25]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
print(a[2])
print(a[2,:])
print(a[:,1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[7 8 9]
[7 8 9]
[ 2  5  8 11]


Note that the last result is also given as a one-dimensional array, i.e. a row. If we want an array that resembles a column, we can use `numpy.reshape()`.

In [26]:
print(a[:,1])
print(np.reshape(a[:,1],(4,1)))

[ 2  5  8 11]
[[ 2]
 [ 5]
 [ 8]
 [11]]


The indexing extends to extracting a subarray (slicing).

In [27]:
a=np.reshape(np.array(range(100)),(5,20))
print(a)
print()
print(a[2:4,10:15])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]

[[50 51 52 53 54]
 [70 71 72 73 74]]


In the above I have used the `numpy.reshape()` function to change a linear array with $100$ entries to a square array of shape $5\times 20$. 

### Array Operations

Arithmetic operators on arrays apply **elementwise**. A new array is created and filled with the result.
In particular `*` multiplies elementwise (a process for matrices also known as the Hadamard product), which has nothing to do with a product of matrices which you will encounter next semester.

In [28]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.eye(3)
c=np.ones((3,3))
print(a)
print(b)
print(c)
print('a+b')
print(a+b)
print('a*b')
print(a*b)
print('b/a')
print(b/a)
print('a**2')
print(a**2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
a+b
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
a*b
[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
b/a
[[1.         0.         0.        ]
 [0.         0.2        0.        ]
 [0.         0.         0.11111111]]
a**2
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


There are many functions in `numpy` that work on arrays, such as `numpy.min` or `numpy.sum`. The nice thing is that we can also apply these commands along the rows or columns.

In [29]:
print(a)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


Note that the last result is also given as a one-dimensional array, i.e. a row. If we want an array that resembles a column, we can again use `numpy.reshape()`.

In [ ]:
print(np.sum(a,axis=1))
print(np.reshape(np.sum(a,axis=1),(3,1)))

Note the difference between `np.sum` and `sum`: `np.sum` sums all the entries, `sum` sums up the columns.

In [ ]:
print(np.sum(a))
print(sum(a))
print(np.sum(a,axis=0))

One operation that is sometimes useful is to transpose arrays, i.e. swap their indices. We can visualise this as reflection along the diagonal with equal indices (i,i).

In [ ]:
a=np.array([[1,2],[3,4]])
print(a)
print(a.T)

### Back to File I/O: Reading and writing numpy data

If your data is in a *standard* format, it is much easier to work with file input/output. For example, a single numpy array can be read and written with the functions `numpy.loadtxt()` and `numpy.savetxt()`. The nice thing is that you don't have to worry about opening or closing files, it is done for you. You just have to specify the filename and the array.

In [ ]:
A=np.random.random((5,3))
print(A)
np.savetxt("test.txt",A)

As this is a plain text file, we can see what it looks like using `readlines()`.

In [ ]:
with open("test.txt",'r') as f:
    for line in f:
        print(line.rstrip())

Let's load this as a new array instead.

In [ ]:
B=np.loadtxt("test.txt")
print(B)

Element-wise comparison shows equality of both arrays.

In [ ]:
print(A==B)

The advantage of the method described here is that the data is stored as a plain text file, which you can easily read. See [here](https://www.python-course.eu/numpy_reading_writing.php) for alternatives involving e.g. binary data.

## An application: solving systems of linear equations.

Next semester you will learn about Linear Algebra, which can help with solving systems of $n$ linear equations in $n$ unknowns.

For $n=2$, these are equations such as
\begin{align*}
3x_0+2x_1&=6\\
-x_0+4x_1&=2
\end{align*}

While this is still easy to solve for $n=2$ (or $3$), computers can do this quickly for much larger values of $n$.

We collect all the coefficients on the left-hand-side in a $2\times 2$-array $A$:
$$
A=\left(\begin{matrix} 3&2\\ -1&4\end{matrix}\right)
$$

The coefficients on the right-hand side form a one-dimensional array $b=(6,2)$ of size $2$, and the unknowns $x_0$ and $x_1$ similarly form a one-dimensional array $x=(x_0,x_1)$ of size $2$.

Let's do this in Python:

In [ ]:
A=np.array([[3,2],[-1,4]])
print(A)
print()
b=[6,2]
print(b)

Having defined $A$ and $b$, there is now a function in the linear algebra module that we can use to find $x$.

In [ ]:
x=la.solve(A,b)
print(x)

We easily identify $x_0=10/7$ and $x_1=6/7$, and we can check
\begin{align*}
3\frac{10}7+2\frac67&=\frac{42}7=6\\
-\frac{10}7+4\frac67y&=\frac{14}7=2
\end{align*}
as required.

But why stop at $n=2$? Let's generate some larger example for, say, $n=6$.

In [ ]:
A=np.random.normal(size=(6,6))
b=np.random.normal(size=(6))
print(A)
print()
print(b)

Let us solve for $x$.

In [ ]:
x=la.solve(A,b)
print(x)

To check the validity, we use an operation called matrix multiplication (more on this next semester). Python does this with the symbol `@`. `x=la.solve(A,b)` solves the matrix equation $Ax=b$, so we need to compute $Ax$ and compare it to $b$.

In [ ]:
print(A@x)
print()
print(b)

This seemed to have worked very well.

Of course I have ignored many issues here: you presumably know already that a system of linear equations may not have any solution, or perhaps more than one, for example. Again, I shall refer to the Linear Algebra module next term.

## Pandas

When it comes to Python, Pandas are not cuddly animals. Rather, Pandas is the name of the *Python Data Analysis Library*, and if you want to do modern data analytics with Python, you will hardly manage to avoid [Pandas](https://pandas.pydata.org/). Its [DataFrame](http://pandas.pydata.org/pandas-docs/stable/reference/frame.html) object is becoming a standard for spreadsheet data. For example, there are ready-made tools available to directly access statistical or financial data from the web. These services are provided by the World Bank, OECD, Eurostat, Nasdaq, and many more.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## A case study: Atmospheric Carbondioxide Data

To show you the strength of Pandas, we present a brief analysis of carbondioxide data from the Mauna Loa observatory on Hawaii (with a resit project focussing on Methane data), readily available online.

This shows how easy it is to

- access live data from the web
- work with spreadsheets in Python (who needs Excel?)
- utilise powerful functionality from special modules (or do it even better from scratch)
- present data in a visually appealing way

The data is available as a csv document: https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_weekly_mlo.csv 

This is the same file format (comma separated values) that Excel can read, so we can just open it directly to have a peek. We see some explanation in the header, followed by neatly arranged data in labelled columns.

But we wish to open it in Python. Except for telling Python where to start reading (we need to skip the top rows and start with the row that has the column labels), we can simply use `pd.read_csv(url_string)`.

In [ ]:
# note the need to skip the top rows (view the file in excel to see the content)
data=pd.read_csv("https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_weekly_mlo.csv",skiprows=35)

So what does this file look like? We can easily look at a neatly formatted output!

In [ ]:
data

We see a typical spreadsheet, with column labels, row labels (in this case just indices), and content in the cells (here just numerical values, it seems).

The column labels are fairly self-explanatory: There are four columns referring to the time of the measurement, one column giving the measured Carbondioxide concentration in ppm (parts per million), and some extra information. Every row corresponds to a weekly averaged measurement, and there are 2582 weeks available, covering roughly 50 years.

We extract the date (in decimal, that seems easiest) and the CO2 concentration.

In [ ]:
Mauna_Loa=data[["decimal","average"]].set_index("decimal")
Mauna_Loa

Let's plot it. All we need to make it look good is some labelling of the axes.

In [ ]:
Mauna_Loa.plot(xlabel="year",ylabel="$CO_2$ [ppm]")
plt.show()

Oops! Looks like we need some data cleaning (notice the -999.9 above - this signifies missing data, it seems). Concentrations should be non-negative, so let's remove all the negative entries and replot.

In [ ]:
filtered=Mauna_Loa[Mauna_Loa["average"]>0] # doesn't this look easy?!?
filtered.plot(xlabel="year",ylabel="$CO_2$ [ppm]")
plt.show()

This looks a lot nicer.

The above is a fairly typical process when looking at real data. We need to inspect the data, select the right data sets (choose columns), understand the content, and possibly clean up some, remove outliers, deal with missing data, and the like.

We can see that there is
- a global trend,
- regular seasonal oscillations, and perhaps 
- residual noise

Courtesy of the module `statsmodels`, there is a simple function to do this all in one fell swoop!

In [ ]:
from statsmodels.tsa.seasonal import seasonal_decompose
plt.rcParams["figure.figsize"]=(12,6) # change the figure size to see things better
seasonal_decompose(pd.Series(filtered["average"]),model="additive",period=52).plot()
plt.show()

Impressive, isn't it?

OK, let us try to do this by hand. We have yearly oscillations, let's take rolling over 52 weeks to get the average over one year.

In [ ]:
Mauna_Loa_cleaned=filtered[["average"]]
Mauna_Loa_cleaned["trend"]=Mauna_Loa_cleaned["average"].rolling(52,center=True).mean()
Mauna_Loa_cleaned.plot()
plt.show()

You see, I just added a column labelled "trend" and simply plot the whole dataframe. The orange line follows the blue oscillating curve nicely. 

If you look closely, you can observe tht the orange line does not extend across the full date range. The reason is that it needs enough data points to compute a rolling mean, and thus 26 weeks are missing on both ends.

Next, I am interested in the difference, so I create another column with label "detrended" and enter the difference between "average" and "trend". 

In [ ]:
Mauna_Loa_cleaned["detrended"]=Mauna_Loa_cleaned["average"]-Mauna_Loa_cleaned["trend"]
Mauna_Loa_cleaned[["detrended"]].plot()
plt.show()

Now get the seasonal effects by taking means over each week of the year (I admit, this is a bit complicated, I needed some serious Googling to do this in just two lines).

In [ ]:
Mauna_Loa_cleaned["week"]=(52*(Mauna_Loa_cleaned.index%1)).astype(int) # extract the week from the index values
Mauna_Loa_cleaned["seasonality"]=Mauna_Loa_cleaned.groupby("week")["detrended"].transform("mean") # take averages over each week (across all 50 years)
Mauna_Loa_cleaned # Note the NaN values for the undefined rolling averages at beginning and end

Plotting this shows a very nice periodic signal - of course the same for every year, the way we have computed it.

In [ ]:
Mauna_Loa_cleaned[["seasonality"]].plot()
plt.show()

Finally, look at what's left (the residual noise):

In [ ]:
Mauna_Loa_cleaned["residual"]=Mauna_Loa_cleaned["average"]-Mauna_Loa_cleaned["trend"]-Mauna_Loa_cleaned["seasonality"]
Mauna_Loa_cleaned["residual"].plot()
plt.show()

This looks much better than the black-box method: the periodicity of the seasonal data is clear, and the residual noise does not have any visible structure left.

To finish, let's mimic the plot from the black box function.

In [ ]:
Mauna_Loa_cleaned.loc[:, ["average","trend","seasonality","residual"]].plot(subplots=True)
plt.show()

**Note: The previous example was all pretty much what I would call black-box coding: you simply chain together some high level functions that do some stuff you don't really know much about in detail, all in a very linear fashion. In other words, there isn't really any proper programming involved. Still, the existence of these high-level functions is what makes Python so incredibly useful!** 

Practically, all you need is Google and some trial-and-error guesswork.

## Conclusion and Outlook

In this lecture we introduced the basics of dealing with arrays in Python and looked at solving systems of linear equations. We then provided a glimpse of Pandas, to be continued next week.